# Generated by Django 6.1.1 on 2026-10-01 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
