# Generated by Django 6.1.1 on 2026-10-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_delete_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherModel',
        ),
    ]
