# Generated by Django 6.1.1 on 2026-10-01 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0002_delete_studentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('basicinfomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user_auth.basicinfomodel')),
                ('roll', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='media/student_img')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('user_auth.basicinfomodel',),
        ),
    ]
